version: "2"

run:
  issues-exit-code: 1
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - misspell
